### ISSUE TITLE
Hide on scroll example

### ISSUE THREAD

**Issue by alanmeier** [bnxm/material_floating_search_bar#1]
Hi there,

First thanks for the package it is really nice. I am fairly new to flutter but do not get how to hide the search bar when I am scrolling a list that is displayed underneath it. I see you can include it as the body of the search bar but would that not hide the list as well ?

If there any example where the search bar gets hidden when the list or map underneath it is being scrolled down.

Thanks
Alan

**Comment by bnxm** [comment]
Hello,

I've added an example in the readme. You will need to use version `0.1.7` for this to work.

Maybe this will help you:

```dart
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FloatingSearchBar(
      // Your pages or just a simple Scaffold...
      body: IndexedStack(
        children: [
          MyAwesomePage(),
        ],
      ),
    );
  }
}

class MyAwesomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    /// Wrap your Scrollable in a FloatingSearchBarScrollNotifier
    /// to indicate that the FloatingSearchBar should react to
    /// scroll events from this Scrollable.
    return FloatingSearchBarScrollNotifier(
      child: ListView.builder(
        itemCount: 42,
        itemBuilder: (_, index) => Item('Item $index'),
      ),
    );
  }
}
```

**Comment by alanmeier** [comment]
Thank you very much will check it out
