### ISSUE TITLE
Error display widget

### ISSUE THREAD

**Issue by danieramiz** [bnxm/material_floating_search_bar#10]
I'm using the widget and so far so good, I love it! 

But would be great if the widget could handle when the query response empty or an error. 
like an emptyBuilder.

Regards,

**Comment by bnxm** [comment]
Hi,

I'm not exactly sure what you mean with 'query response'. If you're calling an api or query a database you should handle the empty or error case in your model/bloc/controller/etc. and then use the `builder` to update your UI accordingly. The `builder` accepts any widget, so really you can display whatever you want in there (for example and error widget when the response is empty).
