### ISSUE TITLE
Small height for FloatingSearchBar

### ISSUE THREAD

**Issue by Aoi-hosizora** [bnxm/material_floating_search_bar#19]
I set a small height for `FloatingSearchBar`, but when the menu opened, the `TextField` will move down. 
Also I want to change the icon button's size and margin, Should I overwrite them in `actions` and `leadingActions` directly?

Here is my code:

```dart
FloatingSearchBar(
  controller: _controller,
  height: 38, // default is 48
  hint: 'Search',
  textInputType: TextInputType.text,
  textInputAction: TextInputAction.search,
  hintStyle: Theme.of(context).textTheme.bodyText2.copyWith(color: Theme.of(context).hintColor),
  queryStyle: Theme.of(context).textTheme.bodyText2,
  elevation: 3.0,
  iconColor: Colors.black54,
  margins: EdgeInsets.only(top: MediaQuery.of(context).padding.top + 6),
  insets: EdgeInsets.symmetric(horizontal: 6),
  padding: EdgeInsets.symmetric(horizontal: 4),
  maxWidth: MediaQuery.of(context).size.width - 8 * 2,
  scrollPadding: EdgeInsets.only(top: 0, bottom: 32),
  openMaxWidth: MediaQuery.of(context).size.width - 8 * 2,
  // ...
)
```

And here are some screenshots:

Menu closed:
![image](https://user-images.githubusercontent.com/31433480/101991636-1a3a3180-3ce9-11eb-86f4-529ce52e96b2.png)

Menu opened:
![image](https://user-images.githubusercontent.com/31433480/101991652-2a521100-3ce9-11eb-85e2-58458864bd47.png)

Icon size with closed menu:
![image](https://user-images.githubusercontent.com/31433480/101991664-3d64e100-3ce9-11eb-8b55-993ff4a0137c.png)

Icon size with opened menu:
![image](https://user-images.githubusercontent.com/31433480/101991764-bf550a00-3ce9-11eb-9712-43764b834aa3.png)

**Comment by davemg3** [comment]
Got the same issue. Looking at the code, it seems more linked to Flutter TextField widget but lets see the answer of this package owner... in case you try to center you searchbar in such red rectangular decoration (having same height of usual flutter action bar) by decreasing the height of floatingsearchbar, you can also modify the margins while keeping the same height for floatingsearchbar (temporary solution) : 
` margins: EdgeInsets.fromLTRB(8, 3, 8, 0),`

**Comment by bnxm** [comment]
Yes, the flutter `TextField` adds that vertical padding unfortunately. I made some adjustments with version `0.2.5` however, which should fix this issue, I hope.

If you want to change the size of the actions, you will have to do this manually as you said with `actions` and `startActions`.

**Comment by Aoi-hosizora** [comment]
@bnxm I have tested the `0.2.6` version and the problem bas been solved. Thx :)

![image](https://user-images.githubusercontent.com/31433480/102988732-57a38800-454f-11eb-8ca9-f417f7c64b9f.png)
