### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by Adam-Langley** [bnxm/material_floating_search_bar#20]
Profiling a simple flutter app which uses the floating search bar, exhibits an idle CPU usage of ~40% on an iPhone 12 Pro.

I have tracked this back to `_buildProgressBar` in `floating_search_app_bar.dart`. An indeterminate `LinearProgressIndicator`, is the culprit.
The cpu cost of this animation is a weakness of flutter, however - material_floating_search_bar has made the unwise decision, to wrap the `LinearProgressIndicator` in an `AnimatedOpacity` widget as a means to 'hide' the progress indicator, when it is not used (widget.progress is `null` or `false`).

The impact of this - is that many developers who do not use, or need the linear progress indicator feature - will be hit by this 40% CPU overhead for no reason.

A workaround, is to always set the `widget.progress` option to `0` - which forces the `LinearProgressIndicator` into determinate mode - hence no animation.

Suggestion: Either change the internal default to `0` instead of `null`/`false` - or remove the `LinearProgressIndicator` from the widget tree if it's not being used.

![image](https://user-images.githubusercontent.com/16373742/102945619-30cf5c80-4523-11eb-8493-01fd447c10a9.png)

**Comment by bnxm** [comment]
Thanks for tracking this down. Version `0.2.5` should fix this now.

Never thought that `LinearProgressIndicator` would have such a high impact on cpu usage. It seems to be more severe on iOS though, as on my OnePlus 7 Pro the idle usage is just between 2-5%, however indeed, with the new version its now at 0% idle usage.

**Comment by Adam-Langley** [comment]
Thanks @bnxm - confirmed 0.2.5 resolves the issue.
