### ISSUE TITLE
How to set alwaysOpen in FloatingSearchBar

### ISSUE THREAD

**Issue by rafid08** [bnxm/material_floating_search_bar#22]
I want FloatingSearchBar always opened so that it will be opened by default at the first time. But there is no alwaysOpen property as the FloatingSearchAppBar has. Is there any solution?

**Comment by apzuk3** [comment]
You can use FloatingSearchBarController  which ahs open and close functions

**Comment by rafid08** [comment]
> 
> 
> You can use FloatingSearchBarController which ahs open and close functions
