### ISSUE TITLE
Support the null-safety version

### ISSUE THREAD

**Issue by al8n** [bnxm/material_floating_search_bar#23]
Please support the null-safety version. Thanks!

**Comment by SamadiPour** [comment]
I am also eagerly waiting for null-safety version

**Comment by JaffaKetchup** [comment]
Same here!

**Comment by romater0** [comment]
You can use this for now , it works 

material_floating_search_bar:
    git:
        url: https://github.com/bnxm/material_floating_search_bar
        ref: master

**Comment by bnxm** [comment]
Done.

**Comment by JaffaKetchup** [comment]
Thanks!
