### ISSUE TITLE
Add autofocus property

### ISSUE THREAD

**Issue by hyouuu** [bnxm/material_floating_search_bar#24]
Hello! Thanks for sharing this search bar!

I'm new to Flutter so not sure if this is the case (nor do I think I'm ready to make PRs yet), but it looks like we could add a `autofocus` property in the search bar's text field easily to allow keyboard to show immediately upon the search bar becomes visible - https://flutter.dev/docs/cookbook/forms/focus

It would be very useful e.g. in my use case there's a search button without the bar initially, and when users tap on the search button they show intent to start typing the query, so they shouldn't need to tap on the bar another time to bring up the keyboard.

**Comment by michaelsoliman1** [comment]
Hello hyouuu, it will definitely be better if it was a property, but you can use a controller to achieve that, simply create a new `FloatingSearchBarController`  then call `FloatingSearchBarController.open();`

it would be something like that:
```
class _SearchBarState extends State<SearchBar> {
  FloatingSearchBarController searchBarController;

  _SearchBarState() : super() {
    searchBarController = FloatingSearchBarController();
  }

  @override
  void initState() {
    super.initState();
    // a workaround to wait for the page to load
    Timer(Duration(milliseconds: 300), () {
      searchBarController.open();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
     // your customized search bar
      body: buildFloatingSearchBar(),
    );
  }

Widget buildFloatingSearchBar() {
    return FloatingSearchBar(
      controller: searchBarController,
      hint: 'Search...',
      ....}
```

**Comment by hyouuu** [comment]
Thanks @michaelsoliman1 this is perfect!
