### ISSUE TITLE
How to place the search bar at bottom?

### ISSUE THREAD

**Issue by iameerhamza** [bnxm/material_floating_search_bar#25]
i want to  place the floating searchbar at the bottom of my screen. can you guide me how you do this?

**Comment by Mohdx** [comment]
Maybe try to put in `bottomNavigationBar:` !!
Or wrap your `body:` content inside `Expanded` then wrap `Expanded` in a `Column`, then under `Expanded` inside the `Column` you can put your `FloatingSearchBar`!

**Comment by iameerhamza** [comment]
Thanks for that i will give it a try.

**Comment by iameerhamza** [comment]
Hello,
i am using your material floating search bar . I cant find any suitable
code for autocomplete places just like in google maps. i will be grateful
if you help me in this .
Regards

**Comment by bnxm** [comment]
Basically, the example application of this package does exactly that. You might want to take a look at that.

**Comment by iameerhamza** [comment]
sorry to bother you again i just kinda need a little help..
[image: image.png]

i cant find these two dart files...
place.dart
search_model.dart
..

can you help me getting these?

Regards.

**Comment by iameerhamza** [comment]
Sorry to disturb you.. i found these...
