### ISSUE TITLE
Is high CPU use when idle normal?

### ISSUE THREAD

**Issue by Proberts** [bnxm/material_floating_search_bar#3]
Is there a feature I can disable to reduce CPU usage when idle?  Switching between displaying a TextField and FloatingSearchBar (from README.md) in a Stack over a GoogleMap, no app interaction:

TextField: All CPU cores 2%-10% (spikes)

FloatingSearchBar: All CPU cores immediately to 60%-65%, slowly increases over the next few minutes to all cores at 90%-100%.

**Comment by bnxm** [comment]
I cannot say for sure, but I haven't experienced performance issues so far when using the widget and I can't think of anything that would be causing this high cpu usage...
