### ISSUE TITLE
[Example]: the url used in the example is deprecated and cause cors error in flutter web

### ISSUE THREAD

**Issue by Mabsten** [bnxm/material_floating_search_bar#32]
In the `example` package, in `lib/search_model.dart`, the url **'https://photon.komoot.de'** is used for http requests but it from October 2020 is deprecated (see the doc in https://github.com/komoot/photon). According to the documentation, the old url still work (redirecting the request), but actually it doesn't allow CORS request, so the example running in browser, as flutter web app, is bugged by the notorious error "Access to XMLHttpRequest .. has been blocked by CORS policy".

So please update the url, from `'https://photon.komoot.de/api/?q=$query'` to `'https://photon.komoot.io/api/?q=$query'`

**Comment by beachpebble** [comment]
I just tried to setup the example and got stuck at this point, Android Studio is giving the error that String can not be assigned to http.get. I'm a newbie, I am not quite sure what change I need to make to get this working.

**Comment by bnxm** [comment]
Thanks @Mabsten

**Comment by Mabsten** [comment]
@beachpebble I think your error was probably correlated to the old url, that cascaded other errors (cors errors are not catched correctly by dart/js and therefore cause unexpected results ). 
Try the example now that the url has been updated.
