### ISSUE TITLE
Failed assertion:  'primaryContext != null': is not true.

### ISSUE THREAD

**Issue by leoafarias** [bnxm/material_floating_search_bar#4]
There are some issues on the way the clearFocus behaves. I have seen two different behaviors which are causing conflicts.
- While tapping `escape` key twice while focused on the search bar causes exception.
- If you are using Focus widget in the app, for other behavior like keyboard shortcuts it does not recover the focus.

**Comment by leoafarias** [comment]
@bnxm When do you think you plan on releasing this fix, as I have a fork running right now, and would like to get back to the pub package.

**Comment by bnxm** [comment]
I published `0.2.0-dev+1` that has this fix included.
