### ISSUE TITLE
Text Editing Controller

### ISSUE THREAD

**Issue by Sangwan5688** [bnxm/material_floating_search_bar#56]
I'm not sure if it's a lack of documentation or what but I'm not able to find the text editing controller here. Text Editing Controller does help to change the text input via code. But I'm not able to find one in the package. Or any other way via which I can provide a pre-entered text when coming from another screen.

**Comment by rmckern** [comment]
Check out issue #11

**Comment by Sangwan5688** [comment]
Got it thanks
