### ISSUE TITLE
Accessing the controller of the TextField in the SearchBar

### ISSUE THREAD

**Issue by OmarYehiaDev** [bnxm/material_floating_search_bar#6]
I'm trying to add voice search feature to this awesome SearchBar but I can't assign the returned string value of the `Listen` function to the query of the TextField inside the SearchBar. I thought this can be done with the `FloatingSearchBarController` but then I realized that it's controling the `FloatingSearchBar` widget itself. So I need help in making this approach possible, please reply ASAP.

**Comment by bnxm** [comment]
Yeah, indeed I forgot to expose a setter for the query on the `FloatingSearchBarController`. Will add this in the next release.

**Comment by OmarYehiaDev** [comment]
Great. Thanks man

**Comment by bnxm** [comment]
I published the pre-release version 0.2.0-dev+1 that now includes a query setter on the controller.

**Comment by OmarYehiaDev** [comment]
> I published the pre-release version 0.2.0-dev+1 that now includes a query setter on the controller.

Great! I've updated the package and I'll use the query setter now. Thanks in advance man
