### ISSUE TITLE
Do not understand how to change body of the page when selecting any option from the search

### ISSUE THREAD

**Issue by Lix-ai** [bnxm/material_floating_search_bar#7]
Hi,
After selecting any search option, how i display on the page any result regarding the selection from the search bar?

Thanks for the Bar!

Thanks in advance,
=]

**Comment by bnxm** [comment]
I'm sorry, but I'm not exactly sure what 'page' and which 'result' you're referring to...

**Comment by OmarYehiaDev** [comment]
> Hi,
> After selecting any search option, how i display on the page any result regarding the selection from the search bar?
> 
> Thanks for the Bar!
> 
> Thanks in advance,
> =]

I think you can use `ListView.builder()` to build your selection items so you can the selected item `index` to show result based on it. I hope it helps

**Comment by Lix-ai** [comment]
Thanks for the answer, i will explain myself:
1. Click on the search bar = list is opened.
2. Select and click on the 'San Francisco' option (for example).
==> Which result to display on the body page = after selecting a search result.
