### ISSUE TITLE
overflow: Overflow.visible

### ISSUE THREAD

**Issue by danieramiz** [bnxm/material_floating_search_bar#8]
When I download the project to run the example, this error was presented to me:

```
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/implicitly_animated_reorderable_list-0.2.3/lib/src/implicitly_animat
ed_reorderable_list.dart:684:7: Error: No named parameter with the name 'overflow'.
      overflow: Overflow.visible,                                       
      ^^^^^^^^                                                          
../../../SDKs/flutter/packages/flutter/lib/src/widgets/basic.dart:3273:3: Context: Found this candidate, but the arguments
don't match.
  Stack({   
```

I search inside the code and looks like the error is with the Stack widget inside implicitly_animated_reorderable_list.dart

line 683:
return Stack(
      //overflow: Overflow.visible,
      children: <Widget>[
        scrollView,
        if (_dragWidget != null) _buildDraggedItem(),
      ],
    );

If we remove the "overflow" parameter inside the Stack widget the error goes. 
Not sure if that's the best approach.

**Comment by bnxm** [comment]
This was an issue in one of the dependencies. I pushed a new commit that should fix this.
