### ISSUE TITLE
How to make list scrollable on small devices

### ISSUE THREAD

**Issue by cliffordh** [bnxm/material_floating_search_bar#9]
If my model contains many items how can I make the expandable  body scrollable to show these items? Right now, the demo cuts off the list when the content reaches the bottom of the screen.

**Comment by bnxm** [comment]
Yes, you're right. I forgot to add `NeverScrollableScrollPhysics` to the list

**Comment by cliffordh** [comment]
@bnxm Verified this works. Thanks.
